services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: gamestoredb
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./inserts.sql:/docker-entrypoint-initdb.d/2-inserts.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: